# Generated by Django 4.1.2 on 2022-11-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blance',
            name='blance',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
