# Generated by Django 4.1.2 on 2022-11-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blance',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
