# Generated by Django 4.1.2 on 2023-01-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balans',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
