# Generated by Django 4.1.2 on 2023-01-03 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_notificationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifikationssendclient',
            name='status_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.notificationstatus'),
        ),
    ]
