# Generated by Django 4.1.2 on 2023-01-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_notifikationssendclient_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifikationssendclient',
            name='status_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
