# Generated by Django 4.1.2 on 2023-01-04 06:11

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_notifikationssendclient_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifikationssendclient',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=billing.models.NotifikationsSendClient.nameFile),
        ),
    ]
