# Generated by Django 4.1.2 on 2023-01-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_paymentsum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsum',
            name='user_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
