# Generated by Django 4.1.2 on 2023-01-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_paymentsum_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balnse',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='PaymentSum',
        ),
        migrations.RenameField(
            model_name='blance',
            old_name='blance',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='blance',
            name='card_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blance',
            name='expire_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blance',
            name='extra_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='blance',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Balnse',
        ),
    ]
