# Generated by Django 4.1.2 on 2022-10-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_cataegor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cataegor',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
