# Generated by Django 4.1.2 on 2022-12-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbacks',
            name='is_cashback',
            field=models.BooleanField(default=False),
        ),
    ]
