# Generated by Django 4.1.2 on 2022-10-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsiter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custumusers',
            name='shops_id',
        ),
        migrations.AddField(
            model_name='custumusers',
            name='shops_id',
            field=models.ManyToManyField(blank=True, null=True, to='regsiter.shops'),
        ),
    ]
