# Generated by Django 4.1.2 on 2022-10-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='payment_summ',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
