# Generated by Django 4.1.2 on 2022-10-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsiter', '0002_remove_custumusers_shops_id_custumusers_shops_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='custumusers',
            name='appSignature',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='shops',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='custumusers',
            name='shops_id',
            field=models.ManyToManyField(blank=True, to='regsiter.shops'),
        ),
    ]
