# Generated by Django 4.1.2 on 2022-10-23 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regsiter', '0002_distric_province_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='categor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regsiter.cataegor'),
        ),
    ]
