# Generated by Django 4.1.2 on 2023-01-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsiter', '0002_alter_shops_name_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='custumusers',
            name='promo_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
