# Generated by Django 4.1.2 on 2023-02-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsiter', '0004_alter_shops_name_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='is_payment',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
